{% set version = "1.1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ryacas
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Ryacas_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Ryacas/Ryacas_{{ version }}.tar.gz
  sha256: 3efdf51877ce40875f64e78bab8318e0f4da3020bb1d2be1cc42479148cd83bc

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-magrittr                 # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libstdcxx !=14.3.0,!=15.1.0           # [win]
  host:
    - r-base
    - r-rcpp >=0.12.0
    - r-magrittr
  run:
    - r-base
    - r-rcpp >=0.12.0
    - r-magrittr
  run_constrained:
    - libstdcxx !=14.3.0,!=15.1.0           # [win]

test:
  commands:
    - $R -e "library('Ryacas')"           # [not win]
    - "\"%R%\" -e \"library('Ryacas')\""  # [win]

about:
  home: https://github.com/r-cas/ryacas, http://www.yacas.org
  license: GPL-2.0-or-later
  summary: Interface to the 'yacas' computer algebra system (<http://www.yacas.org/>).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: Ryacas
# Version: 1.1.3
# Title: R Interface to the 'Yacas' Computer Algebra System
# Authors@R: c( person(given = "Mikkel Meyer", family = "Andersen", email = "mikl@math.aau.dk", role = c("aut", "cre", "cph")), person(given = "Rob", family = "Goedman", email = "goedman@mac.com", role = c("aut", "cph")), person(given = "Gabor", family = "Grothendieck", email = "ggrothendieck@gmail.com", role = c("aut", "cph")), person(given = "Sren", family = "Hjsgaard", email = "sorenh@math.aau.dk", role = c("aut", "cph")), person(given = "Grzegorz", family = "Mazur", email = "teoretyk@gmail.com", role = c("aut", "cph")), person(given = "Ayal", family = "Pinkus", email = "apinkus@xs4all.nl", role = c("aut", "cph")), person(given = "Nemanja", family = "Trifunovic", role = c("cph"), comment = "UTF-8 part of yacas (src/yacas/include/yacas/utf8*)") )
# Maintainer: Mikkel Meyer Andersen <mikl@math.aau.dk>
# Encoding: UTF-8
# Description: Interface to the 'yacas' computer algebra system (<http://www.yacas.org/>).
# Depends: R (>= 3.3.0)
# Imports: Rcpp (>= 0.12.0), stats, methods, magrittr
# LinkingTo: Rcpp
# Suggests: devtools, exams, knitr, Matrix, pkgload, rmarkdown, igraph, testthat (>= 2.1.0), unix, Rmpfr
# License: GPL
# SystemRequirements: C++11
# URL: https://github.com/r-cas/ryacas, http://www.yacas.org
# BugReports: https://github.com/r-cas/ryacas/issues
# RoxygenNote: 7.0.2
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2020-04-14 16:57:44 UTC; mikl
# Author: Mikkel Meyer Andersen [aut, cre, cph], Rob Goedman [aut, cph], Gabor Grothendieck [aut, cph], Sren Hjsgaard [aut, cph], Grzegorz Mazur [aut, cph], Ayal Pinkus [aut, cph], Nemanja Trifunovic [cph] (UTF-8 part of yacas (src/yacas/include/yacas/utf8*))
# Repository: CRAN
# Date/Publication: 2020-04-15 05:50:20 UTC
